name: .NET Framework 4.8 Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: AssetInserter.sln
      Project_Path: AssetInserter/AssetInserter.csproj

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Visual Studio 2022 Build Tools
      run: |
        choco install visualstudio2022-build-tools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktop" --yes

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore Dependencies
      run: nuget restore ${{ env.Solution_Name }}

    - name: Build Solution
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }} /p:Platform=x64 /p:TargetFrameworkVersion=v4.8

    - name: Run Unit Tests
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build_Output
        path: AssetInserter/bin/${{ matrix.configuration }}/
